import { ChevronDownIcon, CircleCheckIcon, MoreIcon, SearchIcon } from './Icons.jsx'
import { t } from '../i18n.js'
import useFastPress from '../hooks/useFastPress.js'
import OverflowText from './OverflowText.jsx'

export default function Header({tab,circle,searchOpen,onSearch,onCircleSelect,onCompleted,onManage,lang='ko'}){
 const fast=useFastPress(),searchLabel=searchOpen?t(lang,'closeSearch'):t(lang,'search'),circleUnread=(circle?.unread||0)+(circle?.unreadDone||0)
 if(tab==='home')return <div className={`head home-head${searchOpen?' search-mode':''}`}><div className="headrow"><h1 className="ttl">{t(lang,'home')}</h1><div className="hicons"><button className="hbtn" data-act="hsearch" {...fast(onSearch)} aria-label={searchLabel}>{searchOpen?'×':<SearchIcon/>}</button>{!searchOpen&&<button className="hbtn" data-act="sheet-open" onClick={onCompleted} aria-label={t(lang,'completed')}><CircleCheckIcon/></button>}</div></div></div>
 if(tab==='circle')return <div className="head circle-head"><div className="headrow">{circle?<button className="ttlbtn" data-act="circle-pick" onClick={onCircleSelect}><span className="circle-emoji">{circle.emoji}</span><span className="circle-title-control"><OverflowText className="circle-title-window" title={circle.name}>{circle.name}</OverflowText><span className="circle-chevron"><ChevronDownIcon/>{circleUnread>0&&<i className="circle-chevron-dot" aria-label={lang==='en'?'Unseen Circle updates':'확인하지 않은 끼리 알림'}/>}</span></span></button>:<h1 className="ttl">{t(lang,'circle')}</h1>}<div className="circle-tools">{circle&&<p className="head-sub">{lang==='en'?'Members':'멤버'} {circle.members?.length||1}</p>}<div className="hicons"><button className="hbtn" data-act="hsearch" {...fast(onSearch)} aria-label={searchLabel}>{searchOpen?'×':<SearchIcon/>}</button>{!searchOpen&&<button className="hbtn completed-head-button" data-act="sheet-open" onClick={onCompleted} aria-label={t(lang,'completed')}><CircleCheckIcon/>{(circle?.unreadDone||0)>0&&<i className="alert-dot"/>}</button>}{circle&&<button className="hbtn" data-act="circle-manage" onClick={onManage} aria-label={t(lang,'manage')}><MoreIcon/></button>}</div></div></div></div>
 return <div className="head more-head"><div className="headrow"><h1 className="ttl">{t(lang,'more')}</h1><div className="hicons"/></div></div>
}
