import { useMemo, useState } from 'react'

export function Sheet({title,subtitle,children,onClose}){
 return <div className="sheetwrap on"><button className="scrim" onClick={onClose}/><section className="sheet"><div className="grab"/><header className="sheethead"><div><b>{title}</b>{subtitle&&<span className="mini">{subtitle}</span>}</div><button className="sheetclose" onClick={onClose} aria-label="닫기">×</button></header><div className="sheetbody">{children}</div></section></div>
}

export function CirclePicker({circles,selected,onSelect,onCreate,onClose}){
 const[code,setCode]=useState('')
 return <Sheet title="끼리 선택" subtitle="함께 쓰는 할 일 목록" onClose={onClose}><div className="pcard join-box"><h3>초대 코드로 참여</h3><p>받은 코드를 입력해 끼리에 참여합니다.</p><div className="join-row"><input className="field" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="예: KKIU-ABCD"/><button className="mbtn primary">참여</button></div></div>{circles.map(c=><button className="suprow" key={c.id} onClick={()=>onSelect(c.id)}><span className="crow-check">{selected===c.id?'✓':c.emoji}</span><span className="smid"><b>{c.name}</b><span>멤버 {c.members?.length||1}명 · 진행 중 {c.tasks.filter(t=>!t.done).length}개</span></span>{c.unread>0&&<span className="circle-badge">{c.unread}</span>}<span className="out">›</span></button>)}<button className="featins" onClick={onCreate}><span className="p">+</span>새 끼리 만들기</button></Sheet>
}

const emojis='😀 😊 🙂 🌿 🐶 🍊 🪁 🌸 🌊 ☀️ 🌳 🧡 🚲 🏠 ✈️ 🎯 🍳 🎈 🧺 🎮 🪴 📚 🏕️ 🎵 🐱 🐰 🦊 🐻 🌙 ⭐ 🔥'.split(' ')
function IdentityEditor({kind,name,setName,emoji,setEmoji,onDone}){
 const[q,setQ]=useState('');const shown=emojis.filter(e=>!q||e.includes(q));return <div className="identity-editor"><header className="identity-editor-head"><div><span className="identity-editor-kicker">{kind==='circle'?'CIRCLE':'MY PROFILE'}</span><h3>{kind==='circle'?'끼리 설정':'내 프로필 설정'}</h3></div><button className="identity-close" onClick={onDone}>×</button></header><div className="identity-editor-body"><label className="identity-field-label">이름</label><div className="identity-name-wrap"><span className="identity-name-preview">{emoji}</span><input className="field" value={name} onChange={e=>setName(e.target.value)}/></div><div className="identity-field-label"><span>이모지</span><span className="identity-selected">선택됨 <b>{emoji}</b></span></div><input className="field" value={q} onChange={e=>setQ(e.target.value)} placeholder="강아지, 꽃, moon, food"/><div className="identity-emoji-grid">{shown.map(e=><button type="button" className={emoji===e?'on':''} onClick={()=>setEmoji(e)} key={e}>{e}</button>)}</div></div><footer className="identity-actions"><button type="button" className="seltxt" onClick={()=>setEmoji(emojis[Math.floor(Math.random()*emojis.length)])}>🎲 랜덤</button><button type="button" className="seltxt identity-save" onClick={onDone}>저장</button></footer></div>
}

export function CircleEditor({circle,profile,onSave,onDelete,onClose}){
 const[name,setName]=useState(circle?.name||''),[emoji,setEmoji]=useState(circle?.emoji||'🌿'),[pn,setPn]=useState(profile?.name||'영롱'),[pe,setPe]=useState(profile?.emoji||'🌿'),[editing,setEditing]=useState(null)
 const save=()=>onSave({name:name.trim()||'새 끼리',emoji,profileName:pn.trim()||'나',profileEmoji:pe})
 if(!circle)return <Sheet title="새 끼리 만들기" onClose={onClose}><IdentityEditor kind="circle" name={name} setName={setName} emoji={emoji} setEmoji={setEmoji} onDone={save}/></Sheet>
 if(editing)return <Sheet title={editing==='circle'?'끼리 설정':'내 프로필 설정'} onClose={()=>setEditing(null)}><IdentityEditor kind={editing} name={editing==='circle'?name:pn} setName={editing==='circle'?setName:setPn} emoji={editing==='circle'?emoji:pe} setEmoji={editing==='circle'?setEmoji:setPe} onDone={()=>{save();setEditing(null)}}/></Sheet>
 return <Sheet title={`${emoji} ${name}`} subtitle="끼리 관리" onClose={onClose}><div className="pcard invite-card"><h3>초대 코드 · <span className="code-chip">{circle.code||'KKIU-HOME'}</span></h3><p>이 코드를 공유하면 멤버가 들어올 수 있어요.</p><button className="rbtn">코드 복사 <span>⎘</span></button></div><button className="rbtn identity-setting" onClick={()=>setEditing('circle')}><span className="mlead"><span className="mrank">{emoji}</span><span><b>끼리</b><em>{name}</em></span></span><span>편집 ›</span></button><button className="rbtn identity-setting" onClick={()=>setEditing('profile')}><span className="mlead"><span className="mrank">{pe}</span><span><b>내 프로필</b><em>{pn}</em></span></span><span>편집 ›</span></button><div className="ghead"><span>멤버 {circle.members?.length||0}명</span></div><div className="member-order-list">{circle.members?.map((m,i)=>{const n=circle.tasks.filter(t=>!t.done&&(t.assignee||t.assignees?.[0])===m.id).length;return <div className="suprow member-order-row" key={m.id}><span className="who">{m.emoji}</span><span className="smid"><b>{m.name}{i===0?' (나)':''}</b><span>진행 중 {n}개</span></span><span className="member-handle">{i===0?'고정':'⠿'}</span></div>})}</div><div className="mdiv"/><button className="rbtn">나가기 <span>›</span></button>{onDelete&&<button className="rbtn danger" onClick={onDelete}>이 끼리 삭제 <em>· 개설자만 가능</em></button>}</Sheet>
}

const today=iso=>{if(!iso)return false;const a=new Date(iso),b=new Date();return a.toDateString()===b.toDateString()}
export function CompletedSheet({tasks,members,circle,onRestore,onDelete,onClear,onClose}){
 const[expanded,setExpanded]=useState(null);const groups=useMemo(()=>[{label:'오늘',items:tasks.filter(t=>today(t.completedAt))},{label:'이전',items:tasks.filter(t=>!today(t.completedAt))}].filter(g=>g.items.length),[tasks])
 return <Sheet title={`✓ 완료됨 ${tasks.length}`} subtitle={`이번 주 ${tasks.filter(t=>Date.now()-new Date(t.completedAt||0).getTime()<7*864e5).length}개 · 누적 ${tasks.length}개`} onClose={onClose}>{!tasks.length?<div className="empty completed-empty"><div className="empty-c"><h3>아직 완료한 일이 없어요</h3><p>체크하면 이곳에 쌓입니다. 동그라미를 다시 누르면 완료 당시 번호로 복원돼요.</p></div></div>:groups.map(g=><section key={g.label}><div className="ghead"><span>{g.label} · {g.items.length}</span><button onClick={()=>onClear(g.items.map(t=>t.id))}>비우기</button></div>{g.items.map(t=><div className={`drow${expanded===t.id?' expanded':''}`} key={t.id} onClick={()=>setExpanded(expanded===t.id?null:t.id)}><button className="ck on" onClick={e=>{e.stopPropagation();onRestore(t.id)}}>✓</button><span className="rankc">#{(t.doneAt??0)+1}</span><span className="dtitle">{t.title}</span>{circle&&<span className="who">{members.find(m=>m.id===(t.assignee||t.assignees?.[0]))?.emoji}</span>}<span className="dtime">{t.completedAt?new Date(t.completedAt).toLocaleDateString('ko-KR'):''}</span><button className="dx" onClick={e=>{e.stopPropagation();onDelete(t.id)}}>×</button></div>)}</section>)}{tasks.length>0&&<button className="rbtn danger" onClick={()=>onClear(tasks.map(t=>t.id))}>완료 목록 전체 비우기</button>}</Sheet>
}
